name: clang-tidy-review

on: [pull_request]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: ZedThree/clang-tidy-review@v0.8.3
      id: review

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
