name: clang-tidy-review

on: [ pull_request ]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - uses: ZedThree/clang-tidy-review@v0.8.3
      id: review
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        build_dir: build
        config_file: ".clang-tidy"

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
