name: clang-tidy-review

on: [pull_request]

jobs:
  build:
    permissions: read-all|write-all
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: ZedThree/clang-tidy-review@v0.8.3
      id: review
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        build_dir: build
        config_file: ".clang-tidy"

    # If there are any comments, fail the check
    - if: steps.review.outputs.total_comments > 0
      run: exit 1
